version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: demo_devops
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    ports:
      - "9906:3306"
  web:
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./back/:/var/www/html/
    ports:
      - "8100:80"
    tty: true