version: "3"
services:
  db:
    platform: linux/x86_64
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: demo_devops
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    ports:
      - "9906:3306"
  web:
    image: img-static-site-example
    build: .
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./back/:/var/www/html/
    ports:
      - "8100:80"
    tty: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1